### ISSUE TITLE
User has a column based on the hex code of which the color of the visual is supposed to render . This was working before and started occuring in Service and Desktop few months back. Issue is only with the color of the visual and not the visual data  has context menu

### ISSUE THREAD

**Issue by Drishti00** [microsoft/charticulator#1081]
[Custom Visual Issue.zip](https://github.com/microsoft/charticulator/files/12172428/Custom.Visual.Issue.zip)

Colors are populated through a column SA COLOR : Based on the value , the visual should have green color and not red

 
<img width="416" alt="image" src="https://github.com/microsoft/charticulator/assets/140616989/50be8fa1-58e0-4529-b2d0-5eec6ddc8602">

•	User was on April version of Desktop and issue happens randomly with this visual. There are many charticulator visuals in the report. User has observed issue only with this visual so far.
•	The visuals above are same but made on different views.
•	If user replicates the values in a new visual, the visual renders with the right color, as per the backend data.
 
•	This was working fine in the same version of desktop a few days back .

Also, the Component sort order isnt coming as expected.

**Comment by zBritva** [comment]
Fixed in https://github.com/microsoft/charticulator/pull/1071

**Comment by Drishti00** [comment]
@zBritva We did try to import the latest version of the visual but still it did not resolve the issue. Anything else which can be tried to resolve this ?

**Comment by zBritva** [comment]
@Drishti00 
The first part of the visual is approved and available on [Appsource page](https://appsource.microsoft.com/en-US/product/power-bi-visuals/ilfatgaliev1696579877540.charticulator_visual_community_view?tab=Overview)
